### ISSUE TITLE
UI has "compilation" problems

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Hybridize-Functions-Refactoring#264]
## Description

Getting a very strange error when invoking the UI:

```
eclipse.buildId=unknown
java.version=18.0.2-ea
java.vendor=Private Build
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -application org.eclipse.ui.ide.workbench
Command-line arguments:  -application org.eclipse.ui.ide.workbench -data /home/rk1424/Workspaces/Hybridize/../runtime-Hybridize -dev file:/home/rk1424/Workspaces/Hybridize/.metadata/.plugins/org.eclipse.pde.core/Eclipse Application/dev.properties -os linux -ws gtk -arch x86_64 -consoleLog -clean

org.eclipse.ui
Error
Tue Oct 10 10:57:06 EDT 2023
Unhandled event loop exception

org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.Error: Unresolved compilation problems: 
	Syntax error, parameterized types are only available if source level is 1.5 or greater
	The method accept(Boolean) in the type Consumer<Boolean> is not applicable for the arguments (boolean)
	Syntax error, annotations are only available if source level is 1.5 or greater
	The method accept(Boolean) in the type Consumer<Boolean> is not applicable for the arguments (boolean)
	Syntax error, parameterized types are only available if source level is 1.5 or greater
	The method accept(Integer) in the type Consumer<Integer> is not applicable for the arguments (int)
	Lambda expressions are allowed only at source level 1.8 or above
	Cannot refer to the non-final local variable key defined in an enclosing scope
	Cannot refer to the non-final local variable valueConsumer defined in an enclosing scope
	The method accept(Integer) in the type Consumer<Integer> is not applicable for the arguments (int)
	Syntax error, annotations are only available if source level is 1.5 or greater
)
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5000)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4480)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: java.lang.Error: Unresolved compilation problems: 
	Syntax error, parameterized types are only available if source level is 1.5 or greater
	The method accept(Boolean) in the type Consumer<Boolean> is not applicable for the arguments (boolean)
	Syntax error, annotations are only available if source level is 1.5 or greater
	The method accept(Boolean) in the type Consumer<Boolean> is not applicable for the arguments (boolean)
	Syntax error, parameterized types are only available if source level is 1.5 or greater
	The method accept(Integer) in the type Consumer<Integer> is not applicable for the arguments (int)
	Lambda expressions are allowed only at source level 1.8 or above
	Cannot refer to the non-final local variable key defined in an enclosing scope
	Cannot refer to the non-final local variable valueConsumer defined in an enclosing scope
	The method accept(Integer) in the type Consumer<Integer> is not applicable for the arguments (int)
	Syntax error, annotations are only available if source level is 1.5 or greater

	at edu.cuny.citytech.refactoring.common.ui.InputPage.<init>(InputPage.java:33)
	at edu.cuny.hunter.hybridize.ui.wizards.HybridizeFunctionRefactoringWizard$HybridizeFunctionsInputPage.<init>(HybridizeFunctionRefactoringWizard.java:38)
	at edu.cuny.hunter.hybridize.ui.wizards.HybridizeFunctionRefactoringWizard.addUserInputPages(HybridizeFunctionRefactoringWizard.java:81)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizard.addPages(RefactoringWizard.java:407)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:633)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation.lambda$0(RefactoringWizardOpenOperation.java:181)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation.run(RefactoringWizardOpenOperation.java:209)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation.run(RefactoringWizardOpenOperation.java:126)
	at org.eclipse.jdt.internal.ui.refactoring.actions.RefactoringStarter.activate(RefactoringStarter.java:41)
	at edu.cuny.hunter.hybridize.ui.wizards.HybridizeFunctionRefactoringWizard.startRefactoring(HybridizeFunctionRefactoringWizard.java:70)
	at edu.cuny.hunter.hybridize.ui.handlers.HybridizeFunctionHandler.execute(HybridizeFunctionHandler.java:59)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommandInContext(LegacyHandlerService.java:440)
	at org.eclipse.ui.internal.quickaccess.providers.CommandElement.execute(CommandElement.java:61)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	... 22 more
```

## Regression

If I open the common projects in the workspace, I don't get the error. Seems related to to the target definition (perhaps an old Eclipse version there?).

**Comment by khatchad** [comment]
> Seems related to to the target definition (perhaps an old Eclipse version there?).

I checked. Seems OK.

**Comment by khatchad** [comment]
Should be fixed by https://github.com/ponder-lab/Common-Eclipse-Refactoring-Framework/compare/v3.8.0...v5.2.0.
